# Generated by Django 5.1.5 on 2025-01-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='age_limit',
            new_name='age_limited',
        ),
    ]
